### PR TITLE
Update README.md to include links to the Firefox extension.

### PR DESCRIPTION
**Pull request by brandonmcclure**
Initial commit of deployment script to deploy to Firefox Add On store

### CODE REVIEW

**Comment by brandonmcclure** [comment]
@MarkIannucci You will need to create an account on the [Firefox site]( https://addons.mozilla.org/en-US/developers/) for me to add you as an author.

**Comment by brandonmcclure** [comment]
@MarkIannucci You will need to create an account on the [Firefox site]( https://addons.mozilla.org/en-US/developers/) for me to add you as an author.

You can view the changes I made to README.md here: [https://github.com/brandonmcclure/ChromeUserWebSearchExtension/tree/FirefoxAddOn](https://github.com/brandonmcclure/ChromeUserWebSearchExtension/tree/FirefoxAddOn)

The deploy script is just a POST call with the .zip file attached. I am having issues getting the authentication working inside of PowerShell. I feel like the issue is when I am computing the HMACSHA256 hash from the JWT JSON message. (line 26)

**Comment by brandonmcclure** [comment]
#25

**Comment by MarkIannucci** [comment]
I created the account on Firefox.  Is there anything else for me to do before merging?

**Pull request merged**
